# Generated by Django 4.2.8 on 2023-12-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('correct_answer', models.IntegerField()),
                ('option1', models.IntegerField()),
                ('option2', models.IntegerField()),
                ('option3', models.IntegerField()),
                ('option4', models.IntegerField()),
            ],
        ),
    ]
